layout_spectrum: 0.4081252
typography_spectrum: 0.8903338
color:
  saturation: 0.380009
  lightness: 0.2697493
  brandStrength: 0.5571838
  rhythmicContrast: 0.4023449
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: My Makerspace
